version: "3.8"
services:
  mq:
    image: ibmcom/mq:latest
    container_name: ibm-mq-dev
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
    ports:
      - "1414:1414"     # MQ listener
      - "9443:9443"     # MQ console (optional)
    restart: unless-stopped