# The git branch we are serving up built artifacts for.
branch: bob

# The URL for the application is of the form: baseUrlPath/gitBranchName
baseUrlPath: samples-cics-java-liberty-springboot-jcics

# The base name for kube resources to make them small enough.
argoAppName: cics-java-liberty-springboot-jcics

# The path of the docker image into our docker registry.
dockerImageName: "cics-java-dev/samples/cics-java-liberty-springboot-jcics"

# The tag used at the end of the container image full name.
containerImageTag: "bob"

# The name of the git repository
gitRepoName: cics-java-liberty-springboot-jcics

# The docker registry we draw images from.
containerRegistry: harbor-cicsk8s.hursley.ibm.com
