plugins
{
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'java'
	id 'eclipse'
	id 'war'
	id 'idea'
}

group = 'com.ibm.cicsdev.springboot'
version = '1.0.0'

// ============================================================================
// Java Configuration
// ============================================================================
java
{
    toolchain
    {
        languageVersion = JavaLanguageVersion.of(java_version)
    }
}

// ============================================================================
// WAR Configuration
// ============================================================================
war
{
    archiveFileName = 'cics-java-liberty-springboot-jcics.war'
}

// Two versions of the WAR would be built, one for embedding into servers like Liberty (plain)
// and a bootWAR which can run standalone and contains all the Tomcat and Spring Boot stuff
// we don't need bootWAR, so disable it.
bootWar { enabled = false }

// If in Eclipse, add Javadoc to the local project classpath
eclipse
{
    classpath
    {
        downloadJavadoc = true
    }
    // Ensures Gradle Refresh sets the WTP context-root and web facet version correctly.
    wtp
    {
        facet
        {
            facet name: 'jst.web', version: '6.1'
        }
        component
        {
            contextPath = 'cics-java-liberty-springboot-jcics'
        }
    }
}

repositories
{
    mavenCentral()
}

dependencies
{
    // Spring Boot web support
    implementation("org.springframework.boot:spring-boot-starter-web")

    // Don't include TomCat in the runtime build
    providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")

    // CICS BOM (as of Sept 2024)
    compileOnly enforcedPlatform("com.ibm.cics:com.ibm.cics.ts.bom:${project.property('cics.bom.version')}")

    // Don't include JCICS in the final build (no need for version because we have BOM)
    compileOnly("com.ibm.cics:com.ibm.cics.server")
}
