kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.argoAppName }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.cicsk8s.hursley.ibm.com"
  rules:
    - host: {{ .Values.argoAppName }}-cics-java-dev.cicsk8s.hursley.ibm.com
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.argoAppName }}
                port:
                  number: 80
            path: /{{ .Values.baseUrlPath }}/{{ .Values.containerImageTag }}
            pathType: Prefix