kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.applicationShortName }}-{{ .Values.branch }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - javadev-cicsk8s.hursley.ibm.com
      secretName: javadev-cert
  rules:
    - host: javadev-cicsk8s.hursley.ibm.com
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.applicationShortName }}-{{ .Values.branch }}
                port:
                  number: 80
            path: /{{ .Values.baseUrlPath }}/{{ .Values.branch}}
            pathType: Prefix
