kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: {{ .Values.applicationShortName }}-{{ .Values.branch }}-initial
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  serviceAccountName: samples-build-bot
  pipelineRef:
    name: {{ .Values.applicationShortName }}-{{ .Values.branch }}-build
  workspaces:
    - name: git-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-temp
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  params:
    - name: gitRepoName
      value: {{ .Values.gitRepoName }}
    - name: distBranch
      value: {{ .Values.branch }}
    - name: containerRegistry
      value: {{ .Values.containerRegistry }}
    - name: refspec
      value: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
