apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.argoAppName }}-publish
#
#
#
spec:
  #
  #
  #
  workspaces:
    - name: git-workspace
  #
  #
  #
  params:
    - name: gitRevision
      type: string
    - name: gitRepoName
      type: string
    - name: gitRepoFullName
      type: string
    - name: containerRegistry
      type: string
    - name: gitTagName
      type: string


  #
  #
  #
  tasks:

    #
    # Clone the sample repo source code into our workspace.
    #
    - name: clone-sample-repo
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: git@github.ibm.com:cics-samples/$(params.gitRepoName).git
        - name: revision
          value: $(params.gitTagName)
        - name: depth
          value: "99999999"
        - name: subdirectory
          value: $(params.gitRepoName)
        - name: refspec
          value: +refs/tags/$(params.gitTagName):refs/tags/$(params.gitTagName)
      workspaces:
        - name: output
          workspace: git-workspace

    - name: publish-to-public-github
      taskRef:
        kind: Task
        name: task-git-tag-publish
      runAfter:
        - clone-sample-repo
      params:
        - name: gitRepoName
          value: $(params.gitRepoName)
        - name: gitOrgName
          value: techcobweb
          # Note: cicsdev is the external organisation name we want to publish to.
          # techcobweb is the public github one owned by mcobbett for testing.
        - name: containerRegistry
          value: $(params.containerRegistry)
        - name: gitTagName
          value: $(params.gitTagName)
      
      workspaces:
        - name: git-workspace
          workspace: git-workspace






